using Curso_C_;

//TipoPrimitivo.ImprimirTipos();
//ExercicioTiposPrimitivos.LerArmazenar();
//ExercicioTiposPrimitivos.InserirIdade();
//ExercicioTiposPrimitivos.NomeCidade();
//ExercicioTiposPrimitivos.InserirUsuario();
//ExercicioTiposPrimitivos.InserirUsuario();
//ExercicioTiposPrimitivos.NomeEIdade();
//ExercicioTiposPrimitivos.NomeECidade();
//ExercicioTiposPrimitivos.NomeEProfissao();
//ExercicioTiposPrimitivos.NomeEOrigem();
//ExercicioTiposPrimitivos.NomeEnumFav();
//ExercicioTiposPrimitivos.NomeEHobbyFav();
//ExercicioTiposPrimitivos.NomeECorFav();
//ExercicioTiposPrimitivos.NomeEFilmeFav();
//ExercicioTiposPrimitivos.NomeEGeneroMusical();
//ExercicioTiposPrimitivos.NomeEAnimalFav();
//ExercicioTiposPrimitivos.NomeEEsporteFav();
//ExercicioTiposPrimitivos.ComidaFav();
//ExercicioTiposPrimitivos.NomeEBandaFav();
//ExercicioTiposPrimitivos.NomeELivroFav();
//ExercicioTiposPrimitivos.NomeELemaFav();